ALTER TABLE stores ADD COLUMN IF NOT EXISTS meta_pixel_id text DEFAULT NULL;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS tiktok_pixel_id text DEFAULT NULL;
ALTER TABLE stores ADD COLUMN IF NOT EXISTS snapchat_pixel_id text DEFAULT NULL;
